name: envio-indexer
contracts:
  - name: BasicCaveatEnforcer
    handler: src/EventHandlers.ts
    events:
      - event: FunctionAllowed(bytes32 indexed delegationHash, bytes4 functionSelector, bool allowed)
      - event: GameActionLimitSet(bytes32 indexed delegationHash, uint256 maxRolls, uint256 maxBuys, uint256 maxRails, uint256 maxFaucets, uint256 maxCooks, uint256 validUntil)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: RateLimitSet(bytes32 indexed delegationHash, uint256 maxCallsPerHour)
      - event: SpendingLimitSet(bytes32 indexed delegationHash, address token, uint256 maxAmount, uint256 validUntil)
      - event: TargetAddressesSet(bytes32 indexed delegationHash, address[] targets)
      - event: TargetAllowed(bytes32 indexed delegationHash, address target)
      - event: TimeLimitSet(bytes32 indexed delegationHash, uint256 validUntil)
  - name: BreadToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: CaveatEnforcerHub
    handler: src/EventHandlers.ts
    events:
      - event: DefaultEnforcerSet(string indexed enforcerType, address indexed enforcer)
      - event: EnforcerAdded(bytes32 indexed delegationHash, address indexed enforcer)
      - event: EnforcerAfterHookFailed(address indexed enforcer, bytes32 indexed delegationHash, string reason)
      - event: EnforcerEnabled(address indexed enforcer, bool enabled)
      - event: EnforcerRemoved(bytes32 indexed delegationHash, address indexed enforcer)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
  - name: ERC6551Account
    handler: src/EventHandlers.ts
    events:
      - event: NFTReceived(address indexed operator, address indexed from, uint256 indexed tokenId, bytes data)
      - event: Withdraw(address indexed owner, uint256 amount)
  - name: ERC6551Registry
    handler: src/EventHandlers.ts
    events:
      - event: AccountCreated(address indexed account, address indexed implementation, uint256 chainId, address tokenContract, uint256 tokenId, uint256 salt)
  - name: FaucetMon
    handler: src/EventHandlers.ts
    events:
      - event: BalanceFunded(address indexed funder, uint256 amount)
      - event: BalanceWithdrawn(address indexed owner, uint256 amount)
      - event: FaucetUsed(address indexed recipient, uint256 amount)
  - name: FinancialCaveatEnforcer
    handler: src/EventHandlers.ts
    events:
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: SpendingLimitSet(bytes32 indexed delegationHash, address indexed token, uint256 maxAmount, uint256 validUntil, uint256 periodLength)
      - event: TimeLimitSet(bytes32 indexed delegationHash, uint256 validUntil)
      - event: TokenSpent(bytes32 indexed delegationHash, address indexed token, uint256 amount)
      - event: TokenWhitelistSet(bytes32 indexed delegationHash, address[] tokens)
      - event: TransferLimitSet(bytes32 indexed delegationHash, address indexed token, uint256 maxTransferAmount, uint256 dailyLimit)
  - name: FoodNFT
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)
      - event: FoodBurned(uint256 indexed tokenId, address indexed owner, address indexed burner, uint256 timestamp)
      - event: MetadataUpdate(uint256 _tokenId)
      - event: MintPriceUpdated(uint256 oldPrice, uint256 newPrice)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - name: FoodScramble
    handler: src/EventHandlers.ts
    events:
      - event: FaucetAmountUpdated(uint256 oldAmount, uint256 newAmount)
      - event: FaucetCooldownUpdated(uint256 oldCooldown, uint256 newCooldown)
      - event: HamburgerMinted(address indexed player, uint256 tokenId)
      - event: IngredientPurchased(address indexed player, uint256 ingredientType, uint256 position)
      - event: PlayerCreated(address indexed tba, uint256 gridIndex)
      - event: PlayerMoved(address indexed player, uint256 newPosition, uint256 roll)
      - event: RailTraveled(address indexed player, uint256 fromPosition, uint256 toPosition)
      - event: TokenBoundAccountCreated(address indexed eoa, address indexed tba, uint256 startPosition)
  - name: GameCaveatEnforcer
    handler: src/EventHandlers.ts
    events:
      - event: FunctionAllowed(bytes32 indexed delegationHash, bytes4 functionSelector, bool allowed)
      - event: GameActionAllowed(bytes32 indexed delegationHash, string action, bool allowed)
      - event: GameActionLimitSet(bytes32 indexed delegationHash, uint256 maxRolls, uint256 maxBuys, uint256 maxRails, uint256 maxFaucets, uint256 maxCooks, uint256 validUntil)
      - event: GameStateSet(bytes32 indexed delegationHash, bool isActive, uint256 maxConsecutiveActions)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: RateLimitSet(bytes32 indexed delegationHash, uint256 maxCallsPerHour)
      - event: TargetAddressesSet(bytes32 indexed delegationHash, address[] targets)
  - name: LettuceToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: MeatToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: PaymentGateway
    handler: src/EventHandlers.ts
    events:
      - event: ERC20PaymentReceived(address indexed payer, address indexed token, uint256 amount, bytes metadata)
      - event: ERC20Withdrawn(address indexed token, address indexed receiver, uint256 amount)
      - event: NativePaymentReceived(address indexed payer, uint256 amount, bytes metadata)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Withdrawn(address indexed receiver, uint256 amount)
  - name: RewardPool
    handler: src/EventHandlers.ts
    events:
      - event: DistributorUpdated(address indexed distributor, bool authorized)
      - event: FundsDeposited(address indexed from, uint256 amount)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: RewardDistributed(address indexed to, uint256 amount, address indexed distributor)
  - name: SpiceToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: TomatoToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
networks:
  - id: 10143
    start_block: 44185532
    contracts:
      - name: BasicCaveatEnforcer
        address:
          - '0x7049E72082e1141702EF8889bDE3E3a31Ccd4ae6'
      - name: BreadToken
        address:
          - '0x7fB4937115fBf4d6549073E06F69762C7Ce5AD3d'
      - name: CaveatEnforcerHub
        address:
          - '0x5B9247aAdF8A3bc7Dc6784BEf7ac261bbE6Eeae9'
      - name: ERC6551Account
        address:
          - '0x09199Fb0190bf91802565dD09B6594f41e6C8c6d'
      - name: ERC6551Registry
        address:
          - '0x10394aBA8b053E2813e153cd7899E70FF2D4C06C'
      - name: FaucetMon
        address:
          - '0xD861c6d71DFaf9F4013a50a9b177C083e90BD006'
      - name: FinancialCaveatEnforcer
        address:
          - '0xa63Bf373ADF07f6C2d6ea9c0C77309959AbDcfa6'
      - name: FoodNFT
        address:
          - '0x1940ebea22dE78D3C091741557D5072C038dD09b'
      - name: FoodScramble
        address:
          - '0x448e78a30509b93D57d013abb58dF44699F9f35a'
      - name: GameCaveatEnforcer
        address:
          - '0x53D0f94f7d582622fD97DdB2E8a6c1bD4b91e35a'
      - name: LettuceToken
        address:
          - '0x7a1D4c76d170D388f7e0F0f5ca980526a6B20737'
      - name: MeatToken
        address:
          - '0x60fbcbA71083EEbB4E3C1B7175d79D56b73Ba5de'
      - name: PaymentGateway
        address:
          - '0x10ab736762ADFd7E3D1C8932c5d3313a862E0548'
      - name: RewardPool
        address:
          - '0xB49A77881a7DBc039aD80592033fFD80cea117d1'
      - name: SpiceToken
        address:
          - '0x54DB2c6D6Df33F9B156061585F35A55759B61f95'
      - name: TomatoToken
        address:
          - '0xE4aE59B941C6d2881d28BD03f10Da57554FCC390'
unordered_multichain_mode: true
preload_handlers: true
