# config untuk single chain index Monad
name: envio-indexer
contracts:
  # ... semua contracts sama ...
networks:
  - id: 10143 # Hanya Monad
    start_block: 39304464
    contracts:
      # ... semua contracts Monad ...
unordered_multichain_mode: false # Single chain mode
preload_handlers: true
