name: envio-indexer
contracts:
  - name: BasicCaveatEnforcer
    handler: src/EventHandlers.ts
    events:
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: SpendingLimitSet(bytes32 indexed delegationHash, address token, uint256 maxAmount, uint256 validUntil)
      - event: TargetAllowed(bytes32 indexed delegationHash, address target)
      - event: TimeLimitSet(bytes32 indexed delegationHash, uint256 validUntil)
  - name: BreadToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: ERC6551Account
    handler: src/EventHandlers.ts
    events:
      - event: NFTReceived(address indexed operator, address indexed from, uint256 indexed tokenId, bytes data)
      - event: Withdraw(address indexed owner, uint256 amount)
  - name: ERC6551Registry
    handler: src/EventHandlers.ts
    events:
      - event: AccountCreated(address indexed account, address indexed implementation, uint256 chainId, address tokenContract, uint256 tokenId, uint256 salt)
  - name: FaucetMon
    handler: src/EventHandlers.ts
    events:
      - event: BalanceFunded(address indexed funder, uint256 amount)
      - event: BalanceWithdrawn(address indexed owner, uint256 amount)
      - event: FaucetUsed(address indexed recipient, uint256 amount)
  - name: FoodNFT
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)
      - event: FoodBurned(uint256 indexed tokenId, address indexed owner, address indexed burner, uint256 timestamp)
      - event: MetadataUpdate(uint256 _tokenId)
      - event: MintPriceUpdated(uint256 oldPrice, uint256 newPrice)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - name: FoodScramble
    handler: src/EventHandlers.ts
    events:
      - event: FaucetAmountUpdated(uint256 oldAmount, uint256 newAmount)
      - event: FaucetCooldownUpdated(uint256 oldCooldown, uint256 newCooldown)
      - event: HamburgerMinted(address indexed player, uint256 tokenId)
      - event: IngredientPurchased(address indexed player, uint256 ingredientType, uint256 position)
      - event: PlayerCreated(address indexed tba, uint256 gridIndex)
      - event: PlayerMoved(address indexed player, uint256 newPosition, uint256 roll)
      - event: RailTraveled(address indexed player, uint256 fromPosition, uint256 toPosition)
      - event: TokenBoundAccountCreated(address indexed eoa, address indexed tba, uint256 startPosition)
  - name: LettuceToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: MeatToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: PaymentGateway
    handler: src/EventHandlers.ts
    events:
      - event: ERC20PaymentReceived(address indexed payer, address indexed token, uint256 amount, bytes metadata)
      - event: ERC20Withdrawn(address indexed token, address indexed receiver, uint256 amount)
      - event: NativePaymentReceived(address indexed payer, uint256 amount, bytes metadata)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Withdrawn(address indexed receiver, uint256 amount)
  - name: RewardPool
    handler: src/EventHandlers.ts
    events:
      - event: DistributorUpdated(address indexed distributor, bool authorized)
      - event: FundsDeposited(address indexed from, uint256 amount)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: RewardDistributed(address indexed to, uint256 amount, address indexed distributor)
  - name: SpiceToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: TomatoToken
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: SpecialBox
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: BoxPriceUpdated(uint256 newPrice)
      - event: Burn(address indexed user, address indexed tba, uint256 tokenId)
      - event: MintBox(address indexed user, address indexed tba, uint256 tokenId)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: PaymentGatewayUpdated(address newGateway)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - name: SpecialBoxStake
    handler: src/EventHandlers.ts
    events:
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: SpecialBoxMinted(address indexed user, address indexed tba, uint256 amount)
      - event: Stake(address indexed user, address indexed tba, uint256 tokenId)
      - event: StakeAll(address indexed user, address indexed tba, uint256[] tokenIds, uint256 totalStaked)
      - event: StakeBatch(address indexed user, address indexed tba, uint256[] tokenIds)
      - event: Unstake(address indexed user, address indexed tba, uint256 tokenId)
      - event: UnstakeBatch(address indexed user, address indexed tba, uint256[] tokenIds)
networks:
  - id: 10143
    start_block: 41886015
    contracts:
      - name: BasicCaveatEnforcer
        address:
          - "0xbd813486C96b3E75720dAD05B683041dc6c86Fa9"
      - name: BreadToken
        address:
          - "0xcF7932Ba9A78C557048d1A3B27c724649ED85ff2"
      - name: ERC6551Account
        address:
          - "0x7FB58EE97CA8a444Edfe0123708DaB97Db4AbcD5"
      - name: ERC6551Registry
        address:
          - "0x6df309dD5A334E590A17D0F558B4E1d5C6d658f8"
      - name: FaucetMon
        address:
          - "0x4c1C0AE60Cb4180EB46d67C77F0157011937fEb3"
      - name: FoodNFT
        address:
          - "0xAf9A5760AD420D8aA658bc3EF1B40B1a7eb57060"
      - name: FoodScramble
        address:
          - "0xa2738c895bB55C3657002fB6C8867b7A304c65d1"
      - name: LettuceToken
        address:
          - "0xCecAC2c4aB0145E9119E9764Ed1D7adf75DBEF14"
      - name: MeatToken
        address:
          - "0x87a44a9B6768709c56f0170968edA931E2da8292"
      - name: PaymentGateway
        address:
          - "0x1dCb189FF485223274987723f9c8E23B37f07DE7"
      - name: RewardPool
        address:
          - "0x15Eba07D1e0F18dceCa02367Fa9cD6138563F857"
      - name: SpiceToken
        address:
          - "0x63d5AbdA3A4356E5Bb295EC19751371737eC4358"
      - name: TomatoToken
        address:
          - "0x472f4784934d39240F093938aD83CcEbCD5e1727"
  - id: 11155111
    start_block: 9278645
    contracts:
      - name: BasicCaveatEnforcer
        address:
          - "0xF6B400C7F9B5bdE70c86c1Da1560F67a423850b9"
      - name: BreadToken
        address:
          - "0xe288906dAA6347bbACC84B10962bD86552cEb60D"
      - name: ERC6551Account
        address:
          - "0x8328a8c35f7D8836B17d1aC53c9dF6cAc0957B8b"
      - name: ERC6551Registry
        address:
          - "0xb4aCdbB0B15cb8A53C74752b9b2eF16E19Eab00A"
      - name: FaucetMon
        address:
          - "0x4db4aF4d8Bdbe6B72D4Bf913f9D516c43646cb8a"
      - name: FoodNFT
        address:
          - "0x2FF46E513a2991d1338014c911B1eA8E7710f48E"
      - name: FoodScramble
        address:
          - "0x30aC836e65034893F55074bC1498505813ebBDe3"
      - name: LettuceToken
        address:
          - "0xE1448b0804F722150Ea7aa437426bba1094847e5"
      - name: MeatToken
        address:
          - "0x89468237dD190018818085CFBBDc20Cf761f6296"
      - name: PaymentGateway
        address:
          - "0x875777Dfd5660e67A19E365AfAFE90144cb11464"
      - name: RewardPool
        address:
          - "0x7bbb15b93749bd7879C26AB2175d8F5504349988"
      - name: SpecialBox
        address:
          - "0x4D0A40CD80E36e86479B6006828bEf78e12D3e44"
      - name: SpecialBoxStake
        address:
          - "0xe2d971375b8C126F49e3a4975A8C3c9f9DFF0A05"
      - name: SpiceToken
        address:
          - "0x4Bb1A960E86B8Cbe666F14567dc26c2C3EE81Ee1"
      - name: TomatoToken
        address:
          - "0xb64542C5f0c0977fEc8afEA8741034a9226E7153"
unordered_multichain_mode: true
preload_handlers: true
