export const BOARD_STYLES = [
  "grid-1 rounded-lg border border-purple-500",
  "grid-2 rounded-lg border border-purple-500",
  "grid-3 rounded-lg border border-purple-500",
  "grid-4 rounded-lg border border-purple-500",
  "grid-5 rounded-lg border border-purple-500",
  "grid-6 rounded-lg border border-purple-500",
  "grid-7 rounded-lg border border-purple-500",
  "grid-8 rounded-lg border border-purple-500",
  "grid-9 rounded-lg border border-purple-500",
  "grid-10 rounded-lg border border-purple-500",
  "grid-11 rounded-lg border border-purple-500",
  "grid-12 rounded-lg border border-purple-500",
  "grid-13 rounded-lg border border-purple-500",
  "grid-14 rounded-lg border border-purple-500",
  "grid-15 rounded-lg border border-purple-500",
  "grid-16 rounded-lg border border-purple-500",
  "grid-17 rounded-lg border border-purple-500",
  "grid-18 rounded-lg border border-purple-500",
  "grid-19 rounded-lg border border-purple-500",
  "grid-20 rounded-lg border border-purple-500",
];
